### ISSUE TITLE
Fix validate function on Admin struct

### ISSUE THREAD

**Issue by zbuchheit** [tmunzer/mistapi-go#1]
Currently there is a validate function on the Admin struct that checks to make sure email, firstname, and lastname are not null, but in the case of an org token is used instead of a user token those fields will actually be null.
Ref: https://github.com/tmunzer/mistapi-go/blame/3ef09e46e7c0416c876983be74a3295e39ead771/mistapi/models/admin.go#L154C35-L169C2

The resulting response from `https://api.ac2.mist.com/api/v1/self` with an org token is 
```
{
    "name": "pulumi-test-token",
    "privileges": [
        {
            "scope": "org",
            "org_id": "redacted",
            "role": "admin",
            "name": "Test Org"
        }
    ]
}
```

**Comment by zbuchheit** [comment]
related issue: https://github.com/Juniper/terraform-provider-mist/issues/3

**Comment by zbuchheit** [comment]
I made an attempt here https://github.com/zbuchheit/mistapi-go/commit/dcdbd737055533d70ac597b0b9a6f8d6bb0f42bc let me know your thoughts and I will open a PR if you think it looks good

**Comment by tmunzer** [comment]
Hi @zbuchheit ,

I updated the Openapi Specs to fix this issue and regenerated the SDK.
This issue should be fixed now.

Thanks

**Comment by zbuchheit** [comment]
this does appear to be fixed in the newest release. Thanks for fixing it so quickly!
